### ISSUE TITLE
Training error Loss is inf or nan

### ISSUE THREAD

**Issue by godpow** [MatteoH2O1999/alphaPoke#1]
C:\Users\CyberKira\Downloads\alphaPoke-main>py train_alpha_poke.py
Insert number of iterations: 200000
Insert policy path: C:\Users\CyberKira\Downloads\alphaPoke-main\policy
Insert battle format: gen8randombattle
Insert log folder: C:\Users\CyberKira\Downloads\alphaPoke-main\logs

Choose which agent to train:
1: DQN single battle
2: Double DQN single battle
2
2022-05-03 22:39:28.472264: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-03 22:40:26.933288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5547 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2070 SUPER, pci bus id: 0000:2d:00.0, compute capability: 7.5
WARNING:tensorflow:From C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\autograph\impl\api.py:377: ReplayBuffer.get_next (from tf_agents.replay_buffers.replay_buffer) is deprecated and will be removed in a future version.
Instructions for updating:
Use `as_dataset(..., single_deterministic_pass=False) instead.
2022-05-03 22:40:40.618384: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
step: 0 - Average return: 0.01817939803004265
WARNING:tensorflow:From C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\util\dispatch.py:1082: calling foldr_v2 (from tensorflow.python.ops.functional_ops) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.foldr(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.foldr(fn, elems))
2022-05-04 00:00:28.472614: E tensorflow/core/kernels/check_numerics_op.cc:292] abnormal_detected_host @0000000203A00700 = {1, 0} Loss is inf or nan
Traceback (most recent call last):
  File "C:\Users\CyberKira\Downloads\alphaPoke-main\train_alpha_poke.py", line 44, in <module>
    train_double_dqn(iterations, policy_path, b_format, log_folder)
  File "C:\Users\CyberKira\Downloads\alphaPoke-main\train_alpha_poke.py", line 27, in train_double_dqn
    agent.train(steps)
  File "C:\Users\CyberKira\Downloads\alphaPoke-main\agents\base_classes\dqn_player.py", line 22, in train
    loss_data = self.agent.train(experience)
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\tf_agents\agents\tf_agent.py", line 330, in train
    loss_info = self._train_fn(
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\tf_agents\utils\common.py", line 188, in with_check_resource_vars
    return fn(*fn_args, **fn_kwargs)
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\tf_agents\agents\dqn\dqn_agent.py", line 395, in _train
    tf.debugging.check_numerics(loss_info.loss, 'Loss is inf or nan')
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 958, in check_numerics
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\framework\ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Loss is inf or nan : Tensor had NaN values [Op:CheckNumerics]

**Comment by godpow** [comment]
@MatteoH2O1999

**Comment by MatteoH2O1999** [comment]
The error was caused because gamma was set to 1.0. This caused the Q values of the network to explode to infinity. It should be fixed now
