### ISSUE TITLE
keyerror 'losses'

### ISSUE THREAD

**Issue by godpow** [MatteoH2O1999/alphaPoke#2]
[keyerror 'losses'.txt](https://github.com/MatteoH2O1999/alphaPoke/files/8637070/keyerror.losses.txt)
WARNING:absl:Found untraced functions such as sequential_585_layer_call_fn, sequential_585_layer_call_and_return_conditional_losses, nest_map_layer_call_fn, nest_map_layer_call_and_return_conditional_losses, lambda_layer_call_fn while saving (showing 5 of 2358). These functions will not be directly callable after loading.
C:\Users\CyberKira\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\saved_model\nested_structure_coder.py:522: UserWarning: Encoding a StructuredValue with type tf_agents.policies.greedy_policy.DeterministicWithLogProb_ACTTypeSpec; loading this StructuredValue will require that this type be imported and registered.
  warnings.warn("Encoding a StructuredValue with type %s; loading this "
Traceback (most recent call last):
  File "C:\Users\CyberKira\Downloads\alphaPoke-main\train_alpha_poke.py", line 44, in <module>
    train_double_dqn(iterations, policy_path, b_format, log_folder)
  File "C:\Users\CyberKira\Downloads\alphaPoke-main\train_alpha_poke.py", line 29, in train_double_dqn
    agent.save_training_data(logs)
  File "C:\Users\CyberKira\Downloads\alphaPoke-main\agents\alpha_poke.py", line 1047, in save_training_data
    for evaluation in self.evaluations["losses"]:
KeyError: 'losses'

**Comment by godpow** [comment]
@MatteoH2O1999
