### ISSUE TITLE
Rank.py issue

### ISSUE THREAD

**Issue by godpow** [MatteoH2O1999/alphaPoke#4]
Hello I'm trying to use the online rank.py but for some reason I'm having issues running it

Traceback (most recent call last):
  File "C:\Users\CyberKira\Downloads\alphaPoke-main (7)\alphaPoke-main\rank.py", line 306, in <module>
    main()
  File "C:\Users\CyberKira\Downloads\alphaPoke-main (7)\alphaPoke-main\rank.py", line 38, in main
    raise InvalidArgumentNumber()
utils.invalid_argument.InvalidArgumentNumber

**Comment by MatteoH2O1999** [comment]
You are not supplying the correct args when you call rank.py. It is not documented because, as I already told you, it is not officially supported. If you still wish to use it, please first read the code to try to understand what the arguments are before opening an issue, as the first line of code inside of main() would have told you that you were missing arguments.
